# Generated by Django 4.2.6 on 2023-10-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_dt_projects', '0006_alter_shippingaddress_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='mobile',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
